<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/13 09:13:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symjobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
